import { LevelData } from '../types/game';
import { TILES } from './constants';

const C = TILES.EMPTY;
const W = TILES.SOLID;
const M = TILES.SMOOTH;
const U = TILES.SPIKE_UP;
const D = TILES.SPIKE_DOWN;
const L = TILES.SPIKE_LEFT;
const R = TILES.SPIKE_RIGHT;
const S = TILES.SPAWN;
const G = TILES.GOAL;
const P = TILES.SPRING;
const K = TILES.KEY;
const B = TILES.DOOR;
const X = TILES.CRUMBLE;
const Y = TILES.DASH_CRYSTAL;
const O = TILES.ONE_WAY;

// Helper to create an 18x18 enclosed room template with smooth anti-cling perimeter walls
function makeRoom18(fill: number[][]): number[][] {
  const cols = 18;
  const rows = 18;
  const grid: number[][] = [];
  for (let r = 0; r < rows; r++) {
    const row: number[] = [];
    for (let c = 0; c < cols; c++) {
      if (r === 0 || r === rows - 1 || c === 0 || c === cols - 1) {
        row.push(M); // Perimeter walls cannot be clung to or wall-jumped on
      } else {
        const cell = (fill[r - 1] && fill[r - 1][c - 1] !== undefined) ? fill[r - 1][c - 1] : C;
        row.push(cell);
      }
    }
    grid.push(row);
  }
  return grid;
}

// 15 Mobile-Optimized Square (18x18) Hardcore Levels
export const LEVELS: LevelData[] = [
  {
    id: 1,
    name: '01: FIRST BLOOD',
    difficulty: 'Hard',
    parTime: 3.8,
    cols: 18,
    rows: 18,
    hint: 'Жми Прыжок для преодоления препятствий и Рывок для ускорения!',
    grid: makeRoom18([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, G, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, W, W, W],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, W, W, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, W, W, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, W, W, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, W, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [S, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [W, W, C, C, C, C, C, C, C, C, C, C, C, C, W, W],
      [W, W, U, U, U, U, U, U, U, U, U, U, U, U, W, W],
    ]),
  },
  {
    id: 2,
    name: '02: WALL CLIMBER',
    difficulty: 'Hard',
    parTime: 4.5,
    cols: 18,
    rows: 18,
    hint: 'Скользи по стенам и жми Прыжок для отскока от стены.',
    grid: makeRoom18([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, G, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, W, W, W, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, W, C, C, W, C, C, C, C, C, C],
      [C, C, C, C, C, C, W, C, C, W, C, C, C, C, C, C],
      [C, C, C, C, C, C, W, C, C, W, C, C, C, C, C, C],
      [C, C, C, C, C, C, W, C, C, W, C, C, C, C, C, C],
      [C, C, C, C, C, C, W, C, C, W, C, C, C, C, C, C],
      [C, C, C, C, C, C, W, C, C, W, C, C, C, C, C, C],
      [C, C, C, C, C, C, W, C, C, W, C, C, C, C, C, C],
      [C, C, C, C, C, C, W, C, C, W, C, C, C, C, C, C],
      [C, C, C, C, C, C, W, C, C, W, C, C, C, C, C, C],
      [C, C, C, C, C, C, W, C, C, W, C, C, C, C, C, C],
      [S, C, C, C, C, C, W, C, C, W, C, C, C, C, C, C],
      [W, W, W, C, C, C, W, C, C, W, C, C, C, W, W, W],
      [W, W, W, U, U, U, W, U, U, W, U, U, U, W, W, W],
    ]),
  },
  {
    id: 3,
    name: '03: AIR DASH AWAKENING',
    difficulty: 'Hard',
    parTime: 4.8,
    cols: 18,
    rows: 18,
    hint: 'Прыгай и жми кнопку РЫВОК. Алмаз в воздухе восстановит рывок!',
    grid: makeRoom18([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, G, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, W, W, W],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, Y, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, W, W, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, Y, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, W, W, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, Y, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [S, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [W, W, C, C, C, C, C, C, C, C, C, C, C, C, W, W],
      [W, W, U, U, U, U, U, U, U, U, U, U, U, U, W, W],
    ]),
  },
  {
    id: 4,
    name: '04: SAW PATROL',
    difficulty: 'Brutal',
    parTime: 5.2,
    cols: 18,
    rows: 18,
    hint: 'Циркулярная пила патрулирует этаж. Проскользни в окно!',
    saws: [
      { startX: 60, startY: 130, targetX: 220, targetY: 130, speed: 85 },
      { startX: 220, startY: 190, targetX: 60, targetY: 190, speed: 100 },
    ],
    grid: makeRoom18([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, G, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, W, W, W],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, W, W, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, W, W, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, W, W, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, W, W, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [S, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [W, W, C, C, C, C, C, C, C, C, C, C, C, C, W, W],
      [W, W, U, U, U, U, U, U, U, U, U, U, U, U, W, W],
    ]),
  },
  {
    id: 5,
    name: '05: CRUMBLING STEPS',
    difficulty: 'Brutal',
    parTime: 4.6,
    cols: 18,
    rows: 18,
    hint: 'Осыпающиеся блоки ломаются под ногами — не останавливайся!',
    grid: makeRoom18([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, G, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, W, W, W],
      [C, C, C, C, C, C, C, C, C, C, C, X, X, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, X, X, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, X, X, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, X, X, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [S, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [W, W, C, C, C, C, C, C, C, C, C, C, C, C, W, W],
      [W, W, U, U, U, U, U, U, U, U, U, U, U, U, W, W],
    ]),
  },
  {
    id: 6,
    name: '06: SPRING VELOCITY',
    difficulty: 'Brutal',
    parTime: 4.4,
    cols: 18,
    rows: 18,
    hint: 'Пружины подбрасывают высоко вверх. В полете используй рывок!',
    grid: makeRoom18([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, G, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, W, W, W],
      [C, C, C, W, W, W, W, W, W, W, W, W, C, C, C, C],
      [C, C, C, D, D, D, D, D, D, D, D, D, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [S, C, C, P, C, C, C, C, P, C, C, C, C, P, C, C],
      [W, W, W, W, C, C, C, C, W, C, C, C, C, W, W, W],
      [W, W, W, W, U, U, U, U, W, U, U, U, U, W, W, W],
    ]),
  },
  {
    id: 7,
    name: '07: LASER TEMPO',
    difficulty: 'Extreme',
    parTime: 6.0,
    cols: 18,
    rows: 18,
    hint: 'Лазеры включаются ритмично. Учитывай тайминг вспышки!',
    lasers: [
      { gridX: 6, gridY: 2, type: 'laser_v', length: 13, period: 2.0, activeTime: 1.0, phaseOffset: 0.0 },
      { gridX: 11, gridY: 2, type: 'laser_v', length: 13, period: 2.0, activeTime: 1.0, phaseOffset: 1.0 },
    ],
    grid: makeRoom18([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, G, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, W, W, W],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, W, W, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, W, W, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, W, W, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, W, W, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [S, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [W, W, C, C, C, C, C, C, C, C, C, C, C, C, W, W],
      [W, W, U, U, U, U, U, U, U, U, U, U, U, U, W, W],
    ]),
  },
  {
    id: 8,
    name: '08: KEY & GUILTY GATE',
    difficulty: 'Extreme',
    parTime: 6.5,
    cols: 18,
    rows: 18,
    hint: 'Возьми золотой ключ, чтобы открыть врата к финишу!',
    grid: makeRoom18([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, B, G, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, B, W, W, W],
      [C, K, C, C, C, C, C, C, C, C, C, C, B, C, C, C],
      [W, W, W, C, C, C, C, C, C, C, C, C, W, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C],
      [C, C, C, C, C, C, C, W, W, C, C, C, W, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C],
      [C, C, C, C, W, W, C, C, C, C, C, C, W, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C],
      [S, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C],
      [W, W, C, C, C, C, C, C, C, C, C, C, W, C, W, W],
      [W, W, U, U, U, U, U, U, U, U, U, U, W, U, W, W],
    ]),
  },
  {
    id: 9,
    name: '09: CRYSTAL CASCADE',
    difficulty: 'Extreme',
    parTime: 5.8,
    cols: 18,
    rows: 18,
    hint: 'Серия рывков по цепочке алмазов без касания земли.',
    grid: makeRoom18([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, G, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, W, W, W],
      [C, C, C, C, C, C, C, C, C, C, C, Y, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, Y, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, Y, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, Y, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [S, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [W, W, C, C, C, C, C, C, C, C, C, C, C, C, W, W],
      [W, W, U, U, U, U, U, U, U, U, U, U, U, U, W, W],
    ]),
  },
  {
    id: 10,
    name: '10: MEAT GRINDER',
    difficulty: 'Nightmare',
    parTime: 7.2,
    cols: 18,
    rows: 18,
    hint: 'Синхронные пилы охраняют коридоры. Быстрый рывок обязателен!',
    saws: [
      { startX: 60, startY: 100, targetX: 220, targetY: 100, speed: 110 },
      { startX: 220, startY: 160, targetX: 60, targetY: 160, speed: 110 },
    ],
    grid: makeRoom18([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, G, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, W, W, W],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, D, D, D, D, D, D, D, D, C, C, C, C],
      [C, C, C, C, W, W, W, W, W, W, W, W, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, W, C, C, W, C, C, W, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, W, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [S, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [W, W, C, C, C, C, C, C, C, C, C, C, C, C, W, W],
      [W, W, U, U, U, U, U, U, U, U, U, U, U, U, W, W],
    ]),
  },
  {
    id: 11,
    name: '11: VERTICAL INFERNO',
    difficulty: 'Nightmare',
    parTime: 7.5,
    cols: 18,
    rows: 18,
    hint: 'Пружины, осыпающиеся камни и шипы на стенах!',
    grid: makeRoom18([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, G, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, W, W, W, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, X, X, C, C, X, X, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, W, C, C, C, C, C, C, W, C, C, C, C],
      [C, C, C, C, W, R, C, C, C, C, L, W, C, C, C, C],
      [C, C, C, C, W, C, C, C, C, C, C, W, C, C, C, C],
      [C, C, C, C, C, C, C, Y, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, X, X, C, C, X, X, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [S, C, C, P, C, C, C, C, C, C, C, C, P, C, C, C],
      [W, W, W, W, C, C, C, C, C, C, C, C, W, W, W, W],
      [W, W, W, W, U, U, U, U, U, U, U, U, W, W, W, W],
    ]),
  },
  {
    id: 12,
    name: '12: LASER LABYRINTH',
    difficulty: 'Nightmare',
    parTime: 8.0,
    cols: 18,
    rows: 18,
    hint: 'Горизонтальные и вертикальные лазерные решетки.',
    lasers: [
      { gridX: 2, gridY: 5, type: 'laser_h', length: 13, period: 2.2, activeTime: 1.1, phaseOffset: 0.0 },
      { gridX: 8, gridY: 2, type: 'laser_v', length: 13, period: 2.2, activeTime: 1.1, phaseOffset: 1.1 },
    ],
    grid: makeRoom18([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, G, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, W, W, W],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, W, W, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, W, W, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, W, W, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, W, W, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [S, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [W, W, C, C, C, C, C, C, C, C, C, C, C, C, W, W],
      [W, W, U, U, U, U, U, U, U, U, U, U, U, U, W, W],
    ]),
  },
  {
    id: 13,
    name: '13: GAUNTLET RUN',
    difficulty: 'Extreme',
    parTime: 7.0,
    cols: 18,
    rows: 18,
    hint: 'Ключ спрятан вверху — забери его и вернись через ловушки.',
    saws: [
      { startX: 140, startY: 80, targetX: 140, targetY: 180, speed: 95 },
    ],
    grid: makeRoom18([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, K, C, C, C, C, C, C, C, C, C, C, B, G, C, C],
      [W, W, W, C, C, C, C, C, C, C, C, C, B, W, W, W],
      [C, C, C, C, C, C, C, C, C, C, C, C, B, C, C, C],
      [C, C, C, C, C, W, W, C, C, C, C, C, W, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C],
      [C, C, C, C, C, C, C, C, W, W, C, C, W, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C],
      [C, C, W, W, C, C, C, C, C, C, C, C, W, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C],
      [S, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C],
      [W, W, C, C, C, C, C, C, C, C, C, C, W, C, W, W],
      [W, W, U, U, U, U, U, U, U, U, U, U, W, U, W, W],
    ]),
  },
  {
    id: 14,
    name: '14: BULLET CYBERSPACE',
    difficulty: 'Impossible',
    parTime: 8.5,
    cols: 18,
    rows: 18,
    hint: 'Две пилы и два лазера. Найди безопасный ритм!',
    saws: [
      { startX: 60, startY: 90, targetX: 220, targetY: 90, speed: 120 },
      { startX: 220, startY: 150, targetX: 60, targetY: 150, speed: 120 },
    ],
    lasers: [
      { gridX: 9, gridY: 2, type: 'laser_v', length: 13, period: 2.0, activeTime: 1.0, phaseOffset: 0.0 },
    ],
    grid: makeRoom18([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, G, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, W, W, W],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, D, D, D, D, D, D, D, D, C, C, C, C],
      [C, C, C, C, W, W, W, W, W, W, W, W, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, W, C, C, C, C, C, C, W, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, W, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [S, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [W, W, C, C, C, C, C, C, C, C, C, C, C, C, W, W],
      [W, W, U, U, U, U, U, U, U, U, U, U, U, U, W, W],
    ]),
  },
  {
    id: 15,
    name: '15: THE APEX OF SPEED',
    difficulty: 'Impossible',
    parTime: 9.9,
    cols: 18,
    rows: 18,
    hint: 'Финальное испытание мастера спидрана. Собери ключ и дойди до триумфа!',
    saws: [
      { startX: 60, startY: 100, targetX: 220, targetY: 100, speed: 130 },
      { startX: 220, startY: 170, targetX: 60, targetY: 170, speed: 130 },
    ],
    lasers: [
      { gridX: 9, gridY: 2, type: 'laser_v', length: 13, period: 2.4, activeTime: 1.2, phaseOffset: 0.5 },
    ],
    grid: makeRoom18([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, K, C, C, C, C, C, C, C, C, C, C, B, G, C, C],
      [W, W, W, C, C, C, C, C, C, C, C, C, B, W, W, W],
      [C, C, C, C, C, C, C, C, C, C, C, C, B, C, C, C],
      [C, C, C, C, D, D, D, D, D, D, D, D, W, C, C, C],
      [C, C, C, C, W, W, W, W, W, W, W, W, W, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C],
      [C, C, C, C, C, C, Y, C, C, Y, C, C, W, C, C, C],
      [C, C, C, C, W, C, C, C, C, C, C, W, W, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C],
      [C, C, W, C, C, C, C, C, C, C, C, C, W, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C],
      [S, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C],
      [W, W, C, C, C, C, C, C, C, C, C, C, W, C, W, W],
      [W, W, U, U, U, U, U, U, U, U, U, U, W, U, W, W],
    ]),
  },
];
