import { LevelData } from '../types/game';
import { TILES } from './constants';

const C = TILES.EMPTY;
const W = TILES.SOLID;
const M = TILES.SMOOTH;
const U = TILES.SPIKE_UP;
const D = TILES.SPIKE_DOWN;
const L = TILES.SPIKE_LEFT;
const R = TILES.SPIKE_RIGHT;
const S = TILES.SPAWN;
const G = TILES.GOAL;
const P = TILES.SPRING;
const K = TILES.KEY;
const B = TILES.DOOR;
const X = TILES.CRUMBLE;
const Y = TILES.DASH_CRYSTAL;
const O = TILES.ONE_WAY;

// Helper to create a 26x16 enclosed room template with smooth anti-cling perimeter walls
function makeRoom(fill: number[][]): number[][] {
  const grid: number[][] = [];
  for (let r = 0; r < 16; r++) {
    const row: number[] = [];
    for (let c = 0; c < 26; c++) {
      if (r === 0 || r === 15 || c === 0 || c === 25) {
        row.push(M); // Perimeter walls cannot be clung to or wall-jumped on
      } else {
        const cell = (fill[r - 1] && fill[r - 1][c - 1] !== undefined) ? fill[r - 1][c - 1] : C;
        row.push(cell);
      }
    }
    grid.push(row);
  }
  return grid;
}

// 15 Brutal Hardcore Levels with Progressive Challenge & Masteries
export const LEVELS: LevelData[] = [
  {
    id: 1,
    name: '01: FIRST BLOOD',
    difficulty: 'Hard',
    parTime: 4.5,
    cols: 26,
    rows: 16,
    hint: 'Удерживай Прыжок для высокого прыжка. Жми X / Shift для Рывка!',
    grid: makeRoom([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, G, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, W, W],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, W, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, W, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, W, W, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, W, W, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [S, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [W, W, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, W, W],
    ]),
  },
  {
    id: 2,
    name: '02: WALL CLIMBER',
    difficulty: 'Hard',
    parTime: 5.2,
    cols: 26,
    rows: 16,
    hint: 'Скользи по стенам и жми Прыжок для отскока от стены.',
    grid: makeRoom([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, G, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, W, W, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, W, C, C, W, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, W, C, C, W, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, W, C, C, W, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, W, C, C, W, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, W, C, C, W, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, W, C, C, W, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, W, C, C, W, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, W, C, C, W, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, W, C, C, W, C, C, C, C, C, C, C, C, C, C],
      [S, C, C, C, C, C, C, C, C, C, W, C, C, W, C, C, C, C, C, C, C, C, C, C],
      [W, W, W, U, U, U, U, U, U, U, W, U, U, W, U, U, U, U, U, U, U, U, W, W],
    ]),
  },
  {
    id: 3,
    name: '03: AIR DASH AWAKENING',
    difficulty: 'Hard',
    parTime: 4.8,
    cols: 26,
    rows: 16,
    hint: 'Прыгай и делай рывок. Алмазы в воздухе моментально восстанавливают и рывок, и прыжок!',
    grid: makeRoom([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, G, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, W, W],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, Y, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, W, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, Y, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, W, W, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, Y, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [S, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [W, W, W, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, W, W],
    ]),
  },
  {
    id: 4,
    name: '04: SAW BLADE CORRIDOR',
    difficulty: 'Brutal',
    parTime: 6.0,
    cols: 26,
    rows: 16,
    hint: 'Циркулярные пилы патрулируют траектории. Рассчитай тайминг!',
    saws: [
      { startX: 120, startY: 100, targetX: 280, targetY: 100, speed: 90 },
      { startX: 280, startY: 160, targetX: 120, targetY: 160, speed: 110 },
    ],
    grid: makeRoom([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, G, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, W, W],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, W, W, C, C, C, C, W, W, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, W, W, C, C, C, C, C, C, C, C, C, C, W, W, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [S, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [W, W, W, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, W, W],
    ]),
  },
  {
    id: 5,
    name: '05: CRUMBLING DESPAIR',
    difficulty: 'Brutal',
    parTime: 5.5,
    cols: 26,
    rows: 16,
    hint: 'Осыпающиеся платформы разрушаются через мгновение после касания.',
    grid: makeRoom([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, G, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, W, W],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, X, X, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, X, X, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, X, X, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, X, X, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, X, X, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [S, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [W, W, W, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, W, W],
    ]),
  },
  {
    id: 6,
    name: '06: SPRING VELOCITY',
    difficulty: 'Brutal',
    parTime: 5.0,
    cols: 26,
    rows: 16,
    hint: 'Пружины подбрасывают тебя высоко в воздух. Комбинируй с рывком!',
    grid: makeRoom([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, G, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, W, W],
      [C, C, C, C, W, W, W, W, W, W, W, W, W, W, W, W, W, W, C, C, C, C, C, C],
      [C, C, C, C, D, D, D, D, D, D, D, D, D, D, D, D, D, D, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [S, C, C, C, P, C, C, C, C, C, P, C, C, C, C, C, P, C, C, C, C, C, C, C],
      [W, W, W, W, W, U, U, U, U, U, W, U, U, U, U, U, W, U, U, U, U, U, W, W],
    ]),
  },
  {
    id: 7,
    name: '07: CRYSTAL ORBIT',
    difficulty: 'Extreme',
    parTime: 6.8,
    cols: 26,
    rows: 16,
    hint: 'Алмазы мгновенно восстанавливают способность к рывку прямо в воздухе.',
    grid: makeRoom([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, G, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, W, W],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, Y, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, Y, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, Y, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [S, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [W, W, W, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, W, W],
    ]),
  },
  {
    id: 8,
    name: '08: LASER TEMPO',
    difficulty: 'Extreme',
    parTime: 7.2,
    cols: 26,
    rows: 16,
    hint: 'Лазеры включаются и выключаются с циклическим интервалом.',
    lasers: [
      { gridX: 7, gridY: 2, type: 'laser_v', length: 12, period: 2.0, activeTime: 1.0, phaseOffset: 0.0 },
      { gridX: 13, gridY: 2, type: 'laser_v', length: 12, period: 2.0, activeTime: 1.0, phaseOffset: 1.0 },
      { gridX: 19, gridY: 2, type: 'laser_v', length: 12, period: 2.0, activeTime: 1.0, phaseOffset: 0.0 },
    ],
    grid: makeRoom([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, G, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, W, W],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, W, W, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, W, W, C, C, C, C, C, C, C, C, W, W, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [S, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [W, W, W, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, W, W],
    ]),
  },
  {
    id: 9,
    name: '09: KEY & GUILTY GATE',
    difficulty: 'Extreme',
    parTime: 7.5,
    cols: 26,
    rows: 16,
    hint: 'Возьми золотой ключ, чтобы растворить фиолетовые врата к порталу.',
    saws: [
      { startX: 180, startY: 80, targetX: 180, targetY: 180, speed: 100 },
    ],
    grid: makeRoom([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, B, G, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, B, W, W, W, W],
      [C, C, K, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, B, C, C, C, C],
      [C, W, W, W, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C, C],
      [C, C, C, C, C, C, C, W, W, C, C, C, C, C, C, C, C, C, C, W, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, W, W, C, C, C, C, C, W, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C, C],
      [S, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C, C],
      [W, W, W, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, W, U, U, W, W],
    ]),
  },
  {
    id: 10,
    name: '10: MEAT GRINDER',
    difficulty: 'Nightmare',
    parTime: 8.0,
    cols: 26,
    rows: 16,
    hint: 'Две синхронные пилы охраняют коридор узких прыжков.',
    saws: [
      { startX: 100, startY: 120, targetX: 260, targetY: 120, speed: 120 },
      { startX: 260, startY: 170, targetX: 100, targetY: 170, speed: 120 },
    ],
    grid: makeRoom([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, G, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, W, W],
      [C, C, C, C, D, D, D, D, D, D, D, D, D, D, D, D, D, D, C, C, C, C, C, C],
      [C, C, C, C, W, W, W, W, W, W, W, W, W, W, W, W, W, W, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, W, C, C, C, C, W, C, C, C, C, W, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [S, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [W, W, W, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, W, W],
    ]),
  },
  {
    id: 11,
    name: '11: THE NEEDLE',
    difficulty: 'Nightmare',
    parTime: 7.0,
    cols: 26,
    rows: 16,
    hint: 'Хирургическая точность: пролети сквозь шипастую расщелину в 1 блок.',
    grid: makeRoom([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, G, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, W, W],
      [C, C, C, C, C, C, C, C, W, W, W, W, W, W, W, W, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, W, D, D, D, D, D, D, W, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, W, C, C, C, C, C, C, W, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, W, C, C, C, C, C, C, W, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, W, C, C, C, C, C, C, W, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, W, U, U, U, U, U, U, W, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, W, W, W, W, W, W, W, W, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [S, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [W, W, W, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, W, W],
    ]),
  },
  {
    id: 12,
    name: '12: PULSE LABYRINTH',
    difficulty: 'Nightmare',
    parTime: 8.5,
    cols: 26,
    rows: 16,
    hint: 'Два лазера перекрывают путь крест-накрест. Запомни интервал.',
    lasers: [
      { gridX: 3, gridY: 6, type: 'laser_h', length: 18, period: 2.4, activeTime: 1.2, phaseOffset: 0.0 },
      { gridX: 12, gridY: 1, type: 'laser_v', length: 12, period: 2.4, activeTime: 1.2, phaseOffset: 1.2 },
    ],
    grid: makeRoom([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, G, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, W, W],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, W, W, C, C, C, C, C, C, W, W, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, W, W, C, C, C, C, C, C, C, C, C, C, W, W, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [S, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [W, W, W, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, W, W],
    ]),
  },
  {
    id: 13,
    name: '13: GAUNTLET OF CRUMBLE',
    difficulty: 'Impossible',
    parTime: 9.0,
    cols: 26,
    rows: 16,
    hint: 'Не останавливайся ни на долю секунды. Все блоки разрушаются под ногами!',
    saws: [
      { startX: 160, startY: 100, targetX: 280, targetY: 100, speed: 130 },
    ],
    grid: makeRoom([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, G, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, W, W],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, X, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, X, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, X, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, X, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, X, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, X, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [S, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [W, W, W, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, W, W],
    ]),
  },
  {
    id: 14,
    name: '14: TOWER OF AGONY',
    difficulty: 'Impossible',
    parTime: 9.8,
    cols: 26,
    rows: 16,
    hint: 'Вертикальный подъем сквозь шипы, отскоки от стен и пилы.',
    saws: [
      { startX: 110, startY: 70, targetX: 110, targetY: 150, speed: 110 },
      { startX: 270, startY: 150, targetX: 270, targetY: 70, speed: 110 },
    ],
    grid: makeRoom([
      [C, C, C, C, C, C, C, C, C, C, C, G, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, W, W, W, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, W, C, C, W, C, C, W, C, C, W, C, C, W, C, C, W, C, C, C, C, C],
      [C, C, C, W, C, C, W, C, C, W, C, C, W, C, C, W, C, C, W, C, C, C, C, C],
      [C, C, C, W, C, C, W, C, C, W, C, C, W, C, C, W, C, C, W, C, C, C, C, C],
      [C, C, C, W, C, C, W, C, C, W, C, C, W, C, C, W, C, C, W, C, C, C, C, C],
      [C, C, C, W, C, C, W, C, C, W, C, C, W, C, C, W, C, C, W, C, C, C, C, C],
      [C, C, C, W, C, C, W, C, C, W, C, C, W, C, C, W, C, C, W, C, C, C, C, C],
      [C, C, C, W, C, C, W, C, C, W, C, C, W, C, C, W, C, C, W, C, C, C, C, C],
      [C, C, C, W, C, C, W, C, C, W, C, C, W, C, C, W, C, C, W, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [S, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [W, W, W, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, W, W],
    ]),
  },
  {
    id: 15,
    name: '15: THE APEX MASTER',
    difficulty: 'Impossible',
    parTime: 12.0,
    cols: 26,
    rows: 16,
    hint: 'Финальное испытание: пружины, кристаллы, ключ, врата и пила смерти!',
    saws: [
      { startX: 190, startY: 90, targetX: 190, targetY: 190, speed: 140 },
    ],
    lasers: [
      { gridX: 9, gridY: 1, type: 'laser_v', length: 12, period: 2.2, activeTime: 1.1, phaseOffset: 0.0 },
    ],
    grid: makeRoom([
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C],
      [C, C, K, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, B, G, C, C, C],
      [C, W, W, W, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, B, W, W, W, W],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, B, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, Y, C, C, C, C, C, C, C, C, W, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C, C],
      [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C, C],
      [S, C, C, P, C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, W, C, C, C, C],
      [W, W, W, W, W, U, U, U, U, U, U, U, U, U, U, U, U, U, U, W, U, U, W, W],
    ]),
  },
];
